# Most basic makefile. 
# Observe the order in which we place the files; also notice
# that we are not explicitly including the .h file, but it 
# is included in the compilation process via the -I flag

mainMake: main.cpp vehicles.cpp cars.cpp bikes.cpp
     gcc -o mainMake main.cpp vehicles.cpp cars.cpp bikes.cpp -I.